AWSTemplateFormatVersion: "2010-09-09"
Description: "A stack containing an Autoscaling Group running a PHP application to which CodeDeploy deploys secrets"
Parameters:
  ImageId:
    Type: "AWS::EC2::Image::Id"
    Description: "Specify the correct AMI ID for your region: https://aws.amazon.com/amazon-linux-ami/"
    Default: "ami-d834aba1" # eu-west-1
Resources:
  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      IamInstanceProfile: !Ref "InstanceProfile"
      ImageId: !Ref "ImageId"
      InstanceType: "t2.micro"
      KeyName: "aws"
      SecurityGroupIds:
        - !Ref "SecurityGroup"
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install httpd24 php71 ruby wget
          sudo service httpd start
          wget https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto
          sudo pip install boto3 # requirement for the secrets utility
      Tags:
        - Key: "CodeDeploySecretsTest"
          Value: "true"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref "InstanceRole"
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: !Sub "${DeploymentArtifactsBucket.Arn}/*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allows HTTP (80) access to the instance from the world"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  CodeDeployApplication:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: "codedeploy-secrets-test"
  CodeDeployDeploymentGroup:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: !Ref "CodeDeployApplication"
      DeploymentGroupName: "testing"
      Ec2TagFilters:
        - Key: "CodeDeploySecretsTest"
          Value: "true"
          Type: "KEY_AND_VALUE"
      ServiceRoleArn: !GetAtt "CodeDeployServiceRole.Arn"
  CodeDeployServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
  DeploymentArtifactsBucket:
    Type: "AWS::S3::Bucket"
